/*
 * This file is generated by jOOQ.
 */
package dal.jooq.tables.records;


import dal.jooq.tables.Departments;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DepartmentsRecord extends UpdatableRecordImpl<DepartmentsRecord> implements Record2<String, String> {

    private static final long serialVersionUID = 532390823;

    /**
     * Setter for <code>employees.departments.dept_no</code>.
     */
    public void setDeptNo(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>employees.departments.dept_no</code>.
     */
    public String getDeptNo() {
        return (String) get(0);
    }

    /**
     * Setter for <code>employees.departments.dept_name</code>.
     */
    public void setDeptName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>employees.departments.dept_name</code>.
     */
    public String getDeptName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return Departments.DEPARTMENTS.DEPT_NO;
    }

    @Override
    public Field<String> field2() {
        return Departments.DEPARTMENTS.DEPT_NAME;
    }

    @Override
    public String component1() {
        return getDeptNo();
    }

    @Override
    public String component2() {
        return getDeptName();
    }

    @Override
    public String value1() {
        return getDeptNo();
    }

    @Override
    public String value2() {
        return getDeptName();
    }

    @Override
    public DepartmentsRecord value1(String value) {
        setDeptNo(value);
        return this;
    }

    @Override
    public DepartmentsRecord value2(String value) {
        setDeptName(value);
        return this;
    }

    @Override
    public DepartmentsRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DepartmentsRecord
     */
    public DepartmentsRecord() {
        super(Departments.DEPARTMENTS);
    }

    /**
     * Create a detached, initialised DepartmentsRecord
     */
    public DepartmentsRecord(String deptNo, String deptName) {
        super(Departments.DEPARTMENTS);

        set(0, deptNo);
        set(1, deptName);
    }
}
