/*
 * This file is generated by jOOQ.
 */
package dal.jooq.tables.records;


import dal.jooq.tables.DeptEmpLatestDate;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeptEmpLatestDateRecord extends TableRecordImpl<DeptEmpLatestDateRecord> implements Record3<Integer, LocalDate, LocalDate> {

    private static final long serialVersionUID = -1661217421;

    /**
     * Setter for <code>employees.dept_emp_latest_date.emp_no</code>.
     */
    public void setEmpNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>employees.dept_emp_latest_date.emp_no</code>.
     */
    public Integer getEmpNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>employees.dept_emp_latest_date.from_date</code>.
     */
    public void setFromDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>employees.dept_emp_latest_date.from_date</code>.
     */
    public LocalDate getFromDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>employees.dept_emp_latest_date.to_date</code>.
     */
    public void setToDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>employees.dept_emp_latest_date.to_date</code>.
     */
    public LocalDate getToDate() {
        return (LocalDate) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, LocalDate, LocalDate> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, LocalDate, LocalDate> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DeptEmpLatestDate.DEPT_EMP_LATEST_DATE.EMP_NO;
    }

    @Override
    public Field<LocalDate> field2() {
        return DeptEmpLatestDate.DEPT_EMP_LATEST_DATE.FROM_DATE;
    }

    @Override
    public Field<LocalDate> field3() {
        return DeptEmpLatestDate.DEPT_EMP_LATEST_DATE.TO_DATE;
    }

    @Override
    public Integer component1() {
        return getEmpNo();
    }

    @Override
    public LocalDate component2() {
        return getFromDate();
    }

    @Override
    public LocalDate component3() {
        return getToDate();
    }

    @Override
    public Integer value1() {
        return getEmpNo();
    }

    @Override
    public LocalDate value2() {
        return getFromDate();
    }

    @Override
    public LocalDate value3() {
        return getToDate();
    }

    @Override
    public DeptEmpLatestDateRecord value1(Integer value) {
        setEmpNo(value);
        return this;
    }

    @Override
    public DeptEmpLatestDateRecord value2(LocalDate value) {
        setFromDate(value);
        return this;
    }

    @Override
    public DeptEmpLatestDateRecord value3(LocalDate value) {
        setToDate(value);
        return this;
    }

    @Override
    public DeptEmpLatestDateRecord values(Integer value1, LocalDate value2, LocalDate value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeptEmpLatestDateRecord
     */
    public DeptEmpLatestDateRecord() {
        super(DeptEmpLatestDate.DEPT_EMP_LATEST_DATE);
    }

    /**
     * Create a detached, initialised DeptEmpLatestDateRecord
     */
    public DeptEmpLatestDateRecord(Integer empNo, LocalDate fromDate, LocalDate toDate) {
        super(DeptEmpLatestDate.DEPT_EMP_LATEST_DATE);

        set(0, empNo);
        set(1, fromDate);
        set(2, toDate);
    }
}
