/*
 * This file is generated by jOOQ.
 */
package dal.jooq.tables.records;


import dal.jooq.enums.EmployeesGender;
import dal.jooq.tables.Employees;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeesRecord extends UpdatableRecordImpl<EmployeesRecord> implements Record6<Integer, LocalDate, String, String, EmployeesGender, LocalDate> {

    private static final long serialVersionUID = -787746367;

    /**
     * Setter for <code>employees.employees.emp_no</code>.
     */
    public void setEmpNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>employees.employees.emp_no</code>.
     */
    public Integer getEmpNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>employees.employees.birth_date</code>.
     */
    public void setBirthDate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>employees.employees.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>employees.employees.first_name</code>.
     */
    public void setFirstName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>employees.employees.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>employees.employees.last_name</code>.
     */
    public void setLastName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>employees.employees.last_name</code>.
     */
    public String getLastName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>employees.employees.gender</code>.
     */
    public void setGender(EmployeesGender value) {
        set(4, value);
    }

    /**
     * Getter for <code>employees.employees.gender</code>.
     */
    public EmployeesGender getGender() {
        return (EmployeesGender) get(4);
    }

    /**
     * Setter for <code>employees.employees.hire_date</code>.
     */
    public void setHireDate(LocalDate value) {
        set(5, value);
    }

    /**
     * Getter for <code>employees.employees.hire_date</code>.
     */
    public LocalDate getHireDate() {
        return (LocalDate) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, LocalDate, String, String, EmployeesGender, LocalDate> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, LocalDate, String, String, EmployeesGender, LocalDate> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Employees.EMPLOYEES_.EMP_NO;
    }

    @Override
    public Field<LocalDate> field2() {
        return Employees.EMPLOYEES_.BIRTH_DATE;
    }

    @Override
    public Field<String> field3() {
        return Employees.EMPLOYEES_.FIRST_NAME;
    }

    @Override
    public Field<String> field4() {
        return Employees.EMPLOYEES_.LAST_NAME;
    }

    @Override
    public Field<EmployeesGender> field5() {
        return Employees.EMPLOYEES_.GENDER;
    }

    @Override
    public Field<LocalDate> field6() {
        return Employees.EMPLOYEES_.HIRE_DATE;
    }

    @Override
    public Integer component1() {
        return getEmpNo();
    }

    @Override
    public LocalDate component2() {
        return getBirthDate();
    }

    @Override
    public String component3() {
        return getFirstName();
    }

    @Override
    public String component4() {
        return getLastName();
    }

    @Override
    public EmployeesGender component5() {
        return getGender();
    }

    @Override
    public LocalDate component6() {
        return getHireDate();
    }

    @Override
    public Integer value1() {
        return getEmpNo();
    }

    @Override
    public LocalDate value2() {
        return getBirthDate();
    }

    @Override
    public String value3() {
        return getFirstName();
    }

    @Override
    public String value4() {
        return getLastName();
    }

    @Override
    public EmployeesGender value5() {
        return getGender();
    }

    @Override
    public LocalDate value6() {
        return getHireDate();
    }

    @Override
    public EmployeesRecord value1(Integer value) {
        setEmpNo(value);
        return this;
    }

    @Override
    public EmployeesRecord value2(LocalDate value) {
        setBirthDate(value);
        return this;
    }

    @Override
    public EmployeesRecord value3(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public EmployeesRecord value4(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public EmployeesRecord value5(EmployeesGender value) {
        setGender(value);
        return this;
    }

    @Override
    public EmployeesRecord value6(LocalDate value) {
        setHireDate(value);
        return this;
    }

    @Override
    public EmployeesRecord values(Integer value1, LocalDate value2, String value3, String value4, EmployeesGender value5, LocalDate value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EmployeesRecord
     */
    public EmployeesRecord() {
        super(Employees.EMPLOYEES_);
    }

    /**
     * Create a detached, initialised EmployeesRecord
     */
    public EmployeesRecord(Integer empNo, LocalDate birthDate, String firstName, String lastName, EmployeesGender gender, LocalDate hireDate) {
        super(Employees.EMPLOYEES_);

        set(0, empNo);
        set(1, birthDate);
        set(2, firstName);
        set(3, lastName);
        set(4, gender);
        set(5, hireDate);
    }
}
