/*
 * This file is generated by jOOQ.
 */
package dal.jooq.entities;


import dal.jooq.entities.tables.DeptEmp;
import dal.jooq.entities.tables.DeptManager;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>employees</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DEPT_EMP_DEPT_NO = Indexes0.DEPT_EMP_DEPT_NO;
    public static final Index DEPT_MANAGER_DEPT_NO = Indexes0.DEPT_MANAGER_DEPT_NO;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DEPT_EMP_DEPT_NO = Internal.createIndex("dept_no", DeptEmp.DEPT_EMP, new OrderField[] { DeptEmp.DEPT_EMP.DEPT_NO }, false);
        public static Index DEPT_MANAGER_DEPT_NO = Internal.createIndex("dept_no", DeptManager.DEPT_MANAGER, new OrderField[] { DeptManager.DEPT_MANAGER.DEPT_NO }, false);
    }
}
