/*
 * This file is generated by jOOQ.
 */
package dal.jooq.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum EmployeesGender implements EnumType {

    M("M"),

    F("F");

    private final String literal;

    private EmployeesGender(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return null;
    }

    @Override
    public Schema getSchema() {
        return null;
    }

    @Override
    public String getName() {
        return "employees_gender";
    }

    @Override
    public String getLiteral() {
        return literal;
    }
}
