/*
 * This file is generated by jOOQ.
 */
package dal.jooq.entities.tables.records;


import dal.jooq.entities.tables.Salaries;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalariesRecord extends UpdatableRecordImpl<SalariesRecord> implements Record4<Integer, Integer, LocalDate, LocalDate> {

    private static final long serialVersionUID = -826459887;

    /**
     * Setter for <code>employees.salaries.emp_no</code>.
     */
    public void setEmpNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>employees.salaries.emp_no</code>.
     */
    public Integer getEmpNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>employees.salaries.salary</code>.
     */
    public void setSalary(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>employees.salaries.salary</code>.
     */
    public Integer getSalary() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>employees.salaries.from_date</code>.
     */
    public void setFromDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>employees.salaries.from_date</code>.
     */
    public LocalDate getFromDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>employees.salaries.to_date</code>.
     */
    public void setToDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>employees.salaries.to_date</code>.
     */
    public LocalDate getToDate() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, LocalDate> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, Integer, LocalDate, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, Integer, LocalDate, LocalDate> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Salaries.SALARIES.EMP_NO;
    }

    @Override
    public Field<Integer> field2() {
        return Salaries.SALARIES.SALARY;
    }

    @Override
    public Field<LocalDate> field3() {
        return Salaries.SALARIES.FROM_DATE;
    }

    @Override
    public Field<LocalDate> field4() {
        return Salaries.SALARIES.TO_DATE;
    }

    @Override
    public Integer component1() {
        return getEmpNo();
    }

    @Override
    public Integer component2() {
        return getSalary();
    }

    @Override
    public LocalDate component3() {
        return getFromDate();
    }

    @Override
    public LocalDate component4() {
        return getToDate();
    }

    @Override
    public Integer value1() {
        return getEmpNo();
    }

    @Override
    public Integer value2() {
        return getSalary();
    }

    @Override
    public LocalDate value3() {
        return getFromDate();
    }

    @Override
    public LocalDate value4() {
        return getToDate();
    }

    @Override
    public SalariesRecord value1(Integer value) {
        setEmpNo(value);
        return this;
    }

    @Override
    public SalariesRecord value2(Integer value) {
        setSalary(value);
        return this;
    }

    @Override
    public SalariesRecord value3(LocalDate value) {
        setFromDate(value);
        return this;
    }

    @Override
    public SalariesRecord value4(LocalDate value) {
        setToDate(value);
        return this;
    }

    @Override
    public SalariesRecord values(Integer value1, Integer value2, LocalDate value3, LocalDate value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalariesRecord
     */
    public SalariesRecord() {
        super(Salaries.SALARIES);
    }

    /**
     * Create a detached, initialised SalariesRecord
     */
    public SalariesRecord(Integer empNo, Integer salary, LocalDate fromDate, LocalDate toDate) {
        super(Salaries.SALARIES);

        set(0, empNo);
        set(1, salary);
        set(2, fromDate);
        set(3, toDate);
    }
}
