/*
 * This file is generated by jOOQ.
 */
package dal.jooq.entities.tables.records;


import dal.jooq.entities.tables.Titles;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TitlesRecord extends UpdatableRecordImpl<TitlesRecord> implements Record4<Integer, String, LocalDate, LocalDate> {

    private static final long serialVersionUID = 383500689;

    /**
     * Setter for <code>employees.titles.emp_no</code>.
     */
    public void setEmpNo(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>employees.titles.emp_no</code>.
     */
    public Integer getEmpNo() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>employees.titles.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>employees.titles.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>employees.titles.from_date</code>.
     */
    public void setFromDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>employees.titles.from_date</code>.
     */
    public LocalDate getFromDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>employees.titles.to_date</code>.
     */
    public void setToDate(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>employees.titles.to_date</code>.
     */
    public LocalDate getToDate() {
        return (LocalDate) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Integer, String, LocalDate> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDate, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Integer, String, LocalDate, LocalDate> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Titles.TITLES.EMP_NO;
    }

    @Override
    public Field<String> field2() {
        return Titles.TITLES.TITLE;
    }

    @Override
    public Field<LocalDate> field3() {
        return Titles.TITLES.FROM_DATE;
    }

    @Override
    public Field<LocalDate> field4() {
        return Titles.TITLES.TO_DATE;
    }

    @Override
    public Integer component1() {
        return getEmpNo();
    }

    @Override
    public String component2() {
        return getTitle();
    }

    @Override
    public LocalDate component3() {
        return getFromDate();
    }

    @Override
    public LocalDate component4() {
        return getToDate();
    }

    @Override
    public Integer value1() {
        return getEmpNo();
    }

    @Override
    public String value2() {
        return getTitle();
    }

    @Override
    public LocalDate value3() {
        return getFromDate();
    }

    @Override
    public LocalDate value4() {
        return getToDate();
    }

    @Override
    public TitlesRecord value1(Integer value) {
        setEmpNo(value);
        return this;
    }

    @Override
    public TitlesRecord value2(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public TitlesRecord value3(LocalDate value) {
        setFromDate(value);
        return this;
    }

    @Override
    public TitlesRecord value4(LocalDate value) {
        setToDate(value);
        return this;
    }

    @Override
    public TitlesRecord values(Integer value1, String value2, LocalDate value3, LocalDate value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TitlesRecord
     */
    public TitlesRecord() {
        super(Titles.TITLES);
    }

    /**
     * Create a detached, initialised TitlesRecord
     */
    public TitlesRecord(Integer empNo, String title, LocalDate fromDate, LocalDate toDate) {
        super(Titles.TITLES);

        set(0, empNo);
        set(1, title);
        set(2, fromDate);
        set(3, toDate);
    }
}
