/*
 * This file is generated by jOOQ.
 */
package dal.jooq;


import dal.jooq.tables.CurrentDeptEmp;
import dal.jooq.tables.Departments;
import dal.jooq.tables.DeptEmp;
import dal.jooq.tables.DeptEmpLatestDate;
import dal.jooq.tables.DeptManager;
import dal.jooq.tables.Salaries;
import dal.jooq.tables.Titles;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employees extends SchemaImpl {

    private static final long serialVersionUID = -1290758270;

    /**
     * The reference instance of <code>employees</code>
     */
    public static final Employees EMPLOYEES = new Employees();

    /**
     * VIEW
     */
    public final CurrentDeptEmp CURRENT_DEPT_EMP = CurrentDeptEmp.CURRENT_DEPT_EMP;

    /**
     * The table <code>employees.departments</code>.
     */
    public final Departments DEPARTMENTS = Departments.DEPARTMENTS;

    /**
     * The table <code>employees.dept_emp</code>.
     */
    public final DeptEmp DEPT_EMP = DeptEmp.DEPT_EMP;

    /**
     * VIEW
     */
    public final DeptEmpLatestDate DEPT_EMP_LATEST_DATE = DeptEmpLatestDate.DEPT_EMP_LATEST_DATE;

    /**
     * The table <code>employees.dept_manager</code>.
     */
    public final DeptManager DEPT_MANAGER = DeptManager.DEPT_MANAGER;

    /**
     * The table <code>employees.employees</code>.
     */
    public final dal.jooq.tables.Employees EMPLOYEES_ = dal.jooq.tables.Employees.EMPLOYEES_;

    /**
     * The table <code>employees.salaries</code>.
     */
    public final Salaries SALARIES = Salaries.SALARIES;

    /**
     * The table <code>employees.titles</code>.
     */
    public final Titles TITLES = Titles.TITLES;

    /**
     * No further instances allowed
     */
    private Employees() {
        super("employees", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            CurrentDeptEmp.CURRENT_DEPT_EMP,
            Departments.DEPARTMENTS,
            DeptEmp.DEPT_EMP,
            DeptEmpLatestDate.DEPT_EMP_LATEST_DATE,
            DeptManager.DEPT_MANAGER,
            dal.jooq.tables.Employees.EMPLOYEES_,
            Salaries.SALARIES,
            Titles.TITLES);
    }
}
