/*
 * This file is generated by jOOQ.
 */
package dal.jooq.entities.tables;


import dal.jooq.entities.Employees;
import dal.jooq.entities.Indexes;
import dal.jooq.entities.Keys;
import dal.jooq.entities.tables.records.DeptManagerRecord;

import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeptManager extends TableImpl<DeptManagerRecord> {

    private static final long serialVersionUID = -708490321;

    /**
     * The reference instance of <code>employees.dept_manager</code>
     */
    public static final DeptManager DEPT_MANAGER = new DeptManager();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeptManagerRecord> getRecordType() {
        return DeptManagerRecord.class;
    }

    /**
     * The column <code>employees.dept_manager.emp_no</code>.
     */
    public final TableField<DeptManagerRecord, Integer> EMP_NO = createField(DSL.name("emp_no"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>employees.dept_manager.dept_no</code>.
     */
    public final TableField<DeptManagerRecord, String> DEPT_NO = createField(DSL.name("dept_no"), org.jooq.impl.SQLDataType.CHAR(4).nullable(false), this, "");

    /**
     * The column <code>employees.dept_manager.from_date</code>.
     */
    public final TableField<DeptManagerRecord, LocalDate> FROM_DATE = createField(DSL.name("from_date"), org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * The column <code>employees.dept_manager.to_date</code>.
     */
    public final TableField<DeptManagerRecord, LocalDate> TO_DATE = createField(DSL.name("to_date"), org.jooq.impl.SQLDataType.LOCALDATE.nullable(false), this, "");

    /**
     * Create a <code>employees.dept_manager</code> table reference
     */
    public DeptManager() {
        this(DSL.name("dept_manager"), null);
    }

    /**
     * Create an aliased <code>employees.dept_manager</code> table reference
     */
    public DeptManager(String alias) {
        this(DSL.name(alias), DEPT_MANAGER);
    }

    /**
     * Create an aliased <code>employees.dept_manager</code> table reference
     */
    public DeptManager(Name alias) {
        this(alias, DEPT_MANAGER);
    }

    private DeptManager(Name alias, Table<DeptManagerRecord> aliased) {
        this(alias, aliased, null);
    }

    private DeptManager(Name alias, Table<DeptManagerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> DeptManager(Table<O> child, ForeignKey<O, DeptManagerRecord> key) {
        super(child, key, DEPT_MANAGER);
    }

    @Override
    public Schema getSchema() {
        return Employees.EMPLOYEES;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEPT_MANAGER_DEPT_NO);
    }

    @Override
    public UniqueKey<DeptManagerRecord> getPrimaryKey() {
        return Keys.KEY_DEPT_MANAGER_PRIMARY;
    }

    @Override
    public List<UniqueKey<DeptManagerRecord>> getKeys() {
        return Arrays.<UniqueKey<DeptManagerRecord>>asList(Keys.KEY_DEPT_MANAGER_PRIMARY);
    }

    @Override
    public List<ForeignKey<DeptManagerRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DeptManagerRecord, ?>>asList(Keys.DEPT_MANAGER_IBFK_1, Keys.DEPT_MANAGER_IBFK_2);
    }

    public dal.jooq.entities.tables.Employees employees() {
        return new dal.jooq.entities.tables.Employees(this, Keys.DEPT_MANAGER_IBFK_1);
    }

    public Departments departments() {
        return new Departments(this, Keys.DEPT_MANAGER_IBFK_2);
    }

    @Override
    public DeptManager as(String alias) {
        return new DeptManager(DSL.name(alias), this);
    }

    @Override
    public DeptManager as(Name alias) {
        return new DeptManager(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DeptManager rename(String name) {
        return new DeptManager(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeptManager rename(Name name) {
        return new DeptManager(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Integer, String, LocalDate, LocalDate> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
